Repository qiskit-community/qiskit-nature-pyscf, pull requests merged in 2024-02, with the labels that each got.

#54 Update intersphinx links and others
  README.md
  docs/conf.py
  qiskit_nature_pyscf/pyscf_ground_state_solver.py
  qiskit_nature_pyscf/qiskit_solver.py
Labels: stable backport potential, type: documentation

#56 Remove qiskit.org links
  CONTRIBUTING.md
  docs/getting_started.rst
  setup.py
Labels: stable backport potential, type: documentation

#58 Changed to install qiskit not qiskit-terra
  .github/actions/install-main-dependencies/action.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/main.yml
Labels: stable backport potential, type: ci

#60 Support Python 3.12
  .github/workflows/main.yml
  constraints.txt
  releasenotes/notes/python-3.12-951eab86dddf803c.yaml
  setup.py
  tox.ini
Labels: stable backport potential
